# Generated by Django 5.1.3 on 2024-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование категории",
                        max_length=50,
                        verbose_name="наименование категории",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Введите описание категории",
                        max_length=150,
                        verbose_name="описание категории",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование",
                        max_length=50,
                        verbose_name="наименование",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Введите описание",
                        max_length=150,
                        verbose_name="описание",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фото",
                        null=True,
                        upload_to="catalog/images",
                        verbose_name="изображение",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Выберите категорию",
                        max_length=150,
                        verbose_name="категория",
                    ),
                ),
                (
                    "price",
                    models.CharField(max_length=150, verbose_name="цена за покупку"),
                ),
                (
                    "created_at",
                    models.DateField(
                        help_text="Дата создания", verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        help_text="Дата измнения",
                        verbose_name="дата послдеднего изменения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "description"],
            },
        ),
    ]
